drop database dbProdutos;
 
create database dbProdutos;
 
use dbProdutos;
 
CREATE TABLE PRODUTOS 

( 

CODIGO INT, 

NOME VARCHAR(50), 

TIPO VARCHAR(25), 

QUANTIDADE INT, 

VALOR DECIMAL(10,2) 

);

INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 1, 'IMPRESSORA', 'INFORMATICA', 200, 600.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 2, 'CAMERA DIGITAL', 'DIGITAIS', 300, 400.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 3, 'DVD PLAYER', 'ELETRONICOS', 250, 500.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 4, 'MONITOR', 'INFORMATICA', 400, 900.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 5, 'TELEVISOR', 'ELETRONICOS', 350, 650.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 6, 'FILMADORA DIGITAL', 'DIGITAIS', 500, 700.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 7, 'CELULAR', 'TELEFONE', 450, 850.00 );
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 8, 'TECLADO', 'INFORMATICA', 300, 450.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 9, 'VIDEOCASSETE', 'ELETRONICOS', 200, 300.00 ); 
INSERT INTO PRODUTOS ( CODIGO, NOME, TIPO, QUANTIDADE, VALOR ) VALUES ( 10, 'MOUSE', 'INFORMATICA', 400, 60.00 );


DESC PRODUTOS;
SELECT * FROM PRODUTOS;


-- pra ver os tipos sem repetição, campos sem repetição
 select distinct tipo from produtos;
 select * from PRODUTOS where tipo = 'INFORMATICA';
 select tipo from produtos order by tipo;


 -- todos os campos e todos os registros dos campos
 select * from produtos where valor >= 600;
 select valor as 'valor' from produtos where valor >= 600.00;

 -- busca por codigo
 select * from produtos where codigo = 1;
